apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/shuu01/test-app
  newName: ghcr.io/shuu01/test-app
  newTag: 2e4f107cca4dacb2bc7472f9ab7158e7564f2379
