apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
images:
- name: ghcr.io/shuu01/test-app
  newName: ghcr.io/shuu01/test-app
  newTag: eb93acc2e327d6505f21d3e78d777774131d7c2b
